//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoleStockSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direcciones()
        {
            this.Pedidos1 = new HashSet<Pedidos>();
            this.Pedidos11 = new HashSet<Pedidos>();
        }
    
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string direccion2 { get; set; }
        public string ciudad { get; set; }
        public string codigo_postal { get; set; }
        public string pais { get; set; }
        public string telefono { get; set; }
        public byte tipo_direccion { get; set; }
        public bool predeterminada { get; set; }
        public string provincia { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos11 { get; set; }
    }
}
