//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoleStockSolutions.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFCEntities : DbContext
    {
        public TFCEntities()
            : base("name=TFCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorías_Estados> Categorías_Estados { get; set; }
        public virtual DbSet<Detalles_Pedidos> Detalles_Pedidos { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Tallas_Marcas> Tallas_Marcas { get; set; }
        public virtual DbSet<Tallas_Universales> Tallas_Universales { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }
        public virtual DbSet<Colores> Colores { get; set; }
        public virtual DbSet<Productos_Colores> Productos_Colores { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
    }
}
